---
- include: install_mariadb.yml
#X#- include: install_httpd.yml
#X#- include: install_php.yml
- include: install_epel.yml

# Download and install ZABBIX for Centos/RHEL version 7
- name: Download ZABBIX Repo - Centos/RHEL 7
  get_url: url={{ zabbixRepository }} dest=/tmp/zabbix.rpm
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: Install ZABBIX Repo - Centos/RHEL 7
  yum:
    name: /tmp/zabbix.rpm
    state: present
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: get {{ zabbixRpmGpgKey }}
  get_url: url={{ zabbixRpmGpgKey }} dest=/tmp/RPM-GPG-KEY-ZABBIX
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: Import a key from a file
  rpm_key: state=present key=/tmp/RPM-GPG-KEY-ZABBIX

<<<<<<< HEAD
- name: Install zabbix-proxy
=======
- name: Install zabbix-server
>>>>>>> origin/master
  yum: name={{ item }} enablerepo=zabbix state=latest disable_gpg_check=no
  with_items:
    - zabbix-agent
    - zabbix-proxy
#X#    - zabbix-server-mysql
#X#    - zabbix-web-mysql
#X#    - zabbix-web-japanese

- name: disabled zabbix repository
  lineinfile: dest=/etc/yum.repos.d/zabbix.repo regexp='^enabled' line="enabled=0"

# Setting database
- name: Create a new database
  mysql_db: name={{ DBName }} state=present encoding=utf8 collation=utf8_bin

- name: Create database user and 'WITH GRANT OPTION'
  mysql_user: name={{ DBUser }} password={{ DBPassword }} priv={{ DBName }}.*:ALL,GRANT state=present

- name: Importing schema file
  shell: mysql -u{{ DBUser }} -p{{ DBPassword }} {{ DBName }} -e "show tables;" | wc -l
  register: zabbixDatabaseTebles
#X#  changed_when: False
- debug: var=zabbixDatabaseTebles
<<<<<<< HEAD
- shell: zcat /usr/share/doc/zabbix-proxy-mysql-*/schema.sql.gz | mysql -u{{ DBUser }} -p{{ DBPassword }} {{ DBName }}
  when: zabbixDatabaseTebles.stdout == "0"

# Setting zabbix_server.conf
- name: Setting zabbix_proxy.conf
  lineinfile: >-
    dest='/etc/zabbix/zabbix_proxy.conf'
=======
- shell: zcat /usr/share/doc/zabbix-proxy-mysql-*/create.sql.gz | mysql -u{{ DBUser }} -p{{ DBPassword }} {{ DBName }}
  when: zabbixDatabaseTebles.stdout == "0"

# Setting zabbix_server.conf
- name: Setting zabbix_server.conf
  lineinfile: >-
    dest='/etc/zabbix/zabbix_server.conf'
>>>>>>> origin/master
    regexp='{{ item.regexp }}'
    insertafter='{{ item.insertafter }}'
    line='{{ item.line }}'
  with_items:
    - regexp: '^ListenPort='
      insertafter: "^# ListenPort="
      line: 'ListenPort={{ ListenPort }}'
    - regexp: '^LogFile='
      insertafter: "^# LogFile="
      line: 'LogFile={{ LogFile }}'
    - regexp: '^DBHost='
      insertafter: "^# DBHost="
      line: 'DBHost={{ DBHost }}'
    - regexp: '^DBName='
      insertafter: "^# DBName="
      line: 'DBName={{ DBName }}'
    - regexp: '^DBUser='
      insertafter: "^# DBUser="
      line: 'DBUser={{ DBUser }}'
    - regexp: '^DBPassword='
      insertafter: "^# DBPassword="
      line: 'DBPassword={{ DBPassword }}'
    - regexp: '^DBPort='
      insertafter: "^# DBPort="
      line: 'DBPort={{ DBPort }}'
    - regexp: '^DBSocket='
      insertafter: "^# DBSocket="
      line: 'DBSocket={{ DBSocket }}'
    - regexp: '^Server='
      insertafter: "^# Server="
      line: 'Server={{ zabbix_server }}'

#X## Copy a new 'zabbix.conf.php' file into place
#X#- template: src=zabbix.conf.php.j2 dest=/etc/zabbix/web/zabbix.conf.php owner=apache group=apache mode=0644
#X#
- name: start zabbix-proxt server 
  service: name=zabbix-proxy state=started enabled=yes

- name: start zabbix-agent 
  service: name=zabbix-agent state=started enabled=yes

- include: update_firewalld.yml
