---
- name: restart mariadb
  service: name=mariadb state=restarted enabled=yes

- name: restart zabbix-agent
  service: name=zabbix-agent state=restarted enabled=yes

- name: restart zabbix-proxy
  service: name=zabbix-proxy state=restarted enabled=yes
